Adding tests to confirm the behaviour of travel if supplied something…
travisjeffery/timecop pull request #369
Opened 2021-11-19 14:41 UTC by andyjdavis

… unparseable

This is a response to this open issue: https://github.com/travisjeffery/timecop/issues/213

I couldn't see an existing test covering this exact behavior so I added one intending to verify the current behavior. In doing that I discovered that the problem behavior described in the issue appears to have already been resolved.

I have submitted this test in a PR as it may be useful to confirm this is the desired behavior. If this test doesn't seem useful or there is already a test covering this then by all means decline this PR.

2021-11-19 16:41 UTC, joshuacronemeyer approved these changes
LGTM

2021-11-19 17:50 UTC, joshuacronemeyer requested changes
Andy this test doesn't pass, and looks like we don't raise for nil. Looking closer at that we don't raise on purpose. We treat a nil argument as traveling to Time.now. We don't want to change that behavior without a good reason because somebody probably depends on it.

For the string case I think the behavior is also correct. We try to parse the string expecting some time information here and the error message is quite detailed.

Having tests for this behavior is a good idea, tho so if you could get these tests right i'd merge them in. Can you do them for the other verbs? freeze, travel, scale? Let me know if you're interested.

2021-11-20 03:21 UTC, andyjdavis commented
The nil test not passing for you is surprising. I will figure out what I did there.

Happy to add tests for all the verbs where it's helpful

2021-11-20 06:36 UTC, andyjdavis commented
The nil test is failing for me too. I'm unsure what I did last night. I will try to be more careful.

There are now tests for travel, freeze and scale. The scale test is slightly different because a different exception type is thrown.

I have included checking the specific exception message. I'm unsure if this risks the tests being too brittle.

2021-11-30 05:58 UTC, andyjdavis commented
hi @joshuacronemeyer was there anything else I needed to do to move this forward? :)

2021-11-30 17:39 UTC, joshuacronemeyer commented
@andyjdavis i'm kicking off the build to see if all the tests pass and i'll try to look at your changes today.

2021-11-30 17:44 UTC, joshuacronemeyer commented
@andyjdavis looks good. I wouldn't mind having the tests be explicit about nil getting treated as now, so if u can confirm we already test for that or add tests i'd appreciate it.  Not sure why the ruby head build has failed, but looks build related and not to do with your changes so we'll ignore that until we see it fail again.

2021-12-18 14:40 UTC, andyjdavis commented
@joshuacronemeyer I couldn't see any tests covering this specifically so I have added them. Let me know if they are not what you had in mind.

Also, apologies for taking so long to get back to this.

2022-01-14 17:25 UTC, joshuacronemeyer commented
thanks @andyjdavis appreciate you following up here. LGTM.

2022-01-14 17:25 UTC, merged